UMS_MVC/Controllers/EvaluationMatters/EvaluationController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using UMS_MVC.DataModel.Models;
using UMS_MVC.DataModel.Models.Essential_Types;
using UMS_MVC.DataModel.Models.TeacherEvaluation;
using UMS_MVC.Manager.DAL.BLL.TeachersEvaluationManager;
using UMS_MVC.Manager.DAL.DAO;
using UMS_MVC.ViewModels.ViewModels;

namespace UMS_MVC.Controllers.EvaluationMatters
{
    public class EvaluationController : Controller
    {

        private readonly EvaluationConfigurationLogicManager _configurationLogicManager;
        private readonly EvaluationResultLogicManager _resultLogicManager;
        private readonly SurveyAssesmentLogicManager _assesmentLogicManager;
        private readonly SurveyQuestionsLogicManager _questionsLogicManager;
        private readonly SemesterManager _semesterManager;
        private readonly CourseForStudentManger _courseForStudentManger;
        private readonly SectionManager _sectionManager;
        private readonly StudentManager _studentManager;
        private readonly CourseForDepartmentManager _courseForDepartmentManager;

        public EvaluationController()
        {

            _configurationLogicManager = new EvaluationConfigurationLogicManager();
            _resultLogicManager = new EvaluationResultLogicManager();
            _assesmentLogicManager = new SurveyAssesmentLogicManager();
            _questionsLogicManager = new SurveyQuestionsLogicManager();
            _semesterManager = new SemesterManager();
            _courseForStudentManger = new CourseForStudentManger();
            _sectionManager = new SectionManager();
            _studentManager = new StudentManager();
            _courseForDepartmentManager = new CourseForDepartmentManager();
        }
        //survey answer logic manager is static
        // GET: Evaluation
        public ActionResult Index()
        {
            if (Session["UserObj"] == null) return RedirectToAction("LogInresultSubmit", "Home");
            var account = (Account)Session["UserObj"];
            if (account.AccountsRole.AccountType != "Admin") return RedirectToAction("NotPermitted", "Home");
            var config =
                _configurationLogicManager.GetAllEvaluationConfigurations().Include(s => s.Semester).OrderByDescending(s => s.EvaluationConfigurationId);
            var allSemesterForDropdown = _semesterManager.GetAllSemesterFiltered();
            ViewBag.semesterId = new SelectList(allSemesterForDropdown, "SemesterId", "SemesterNYear");
            return View(config.ToList());
        }

        public PartialViewResult ConfigDataPartial(int id = 0)
        {
            var allSemesterForDropdown = _semesterManager.GetAllSemesterFiltered();
            var evaluationConfiguration = new EvaluationConfiguration { SemesterId = 1 };
            if (id != 0)
            {
                evaluationConfiguration = _configurationLogicManager.FindConfiguration(id);
            }
            TempData["semesterId"] = new SelectList(allSemesterForDropdown, "SemesterId", "SemesterNYear", evaluationConfiguration.SemesterId);
            return PartialView("_configDataPartial", evaluationConfiguration);
        }

        public string UpdateEvaluation(EvaluationConfiguration configuration)
        {
            var account = (Account)Session["UserObj"];
            if (configuration.EvaluationConfigurationId != 0)
            {
                var evaluationConfiguration = _configurationLogicManager.FindConfiguration(configuration.EvaluationConfigurationId);
                evaluationConfiguration.SemesterId = configuration.SemesterId;
                evaluationConfiguration.StartDate = configuration.StartDate;
                evaluationConfiguration.EndDate = configuration.EndDate;
                evaluationConfiguration.RemoveEvaluationDate = DateTime.Now;
                evaluationConfiguration.RemovedBy = account.Name;
                evaluationConfiguration.Remarks = configuration.Remarks;

                _configurationLogicManager.UpdateConfiguration(evaluationConfiguration);
                return "Successfully Updated";
            }
            if (configuration.EvaluationConfigurationId == 0)
            {
                _configurationLogicManager.InsertConfiguration(configuration);
                return "Successfully Added";
            }
            return "Error in Update Process";
        }

        public PartialViewResult AssessmentDataPartial(int semesterId = 0)
        {
            try
            {
                if (semesterId > 0)
                {
                    //var assesmentQuery = _assesmentLogicManager.GetAllSurveyAssesment().AsQueryable();

                    var getSections =
                      _sectionManager.GetAllSectionBySemester(semesterId)
                          .Include(s => s.CourseForStudentsAcademics)
                          .Include(s => s.Semester)
                          .Select(s => new DataAssessmentViewModel
                          {

                              SectionId = s.SectionId,
                              CourseName = s.CourseForDepartment.CourseName,
                              SemesterName = s.Semester.SemesterNYear,
                              TotalStudent = s.CourseForStudentsAcademics.Count(),
                              UncompletedSurvey = s.CourseForStudentsAcademics.Count(x => !x.EvaluationComplete),
                              CompletedSurvey = s.CourseForStudentsAcademics.Count(x => x.EvaluationComplete)

                          }).ToList();

                    return PartialView("_assessmentDataPartial", getSections);
                }

            }
            catch (Exception exception)
            {

            }

            return PartialView("_assessmentDataPartial", null);
        }
        public string RemoveAssData(int id)
        {
            if (id <= 0) return "An error occured during removing !!";
            try
            {
                var getStudentsAcaId = _courseForStudentManger.GetAllCourseForStudentsAcademicsFiltered().Where(s => s.SectionId == id).ToList();
                foreach (var i in getStudentsAcaId)
                {
                    var getAcaIdWiseDataAssessment =
                        _assesmentLogicManager.GetAllSurveyAssesment()
                            .Where(s => s.CourseForStudentsAcademicId == i.CourseForStudentsAcademicId);
                    foreach (var j in getAcaIdWiseDataAssessment.ToList())
                    {
                        _assesmentLogicManager.DeleteAssesment(j.SurveryAssesmentId);
                    }
                }
                _assesmentLogicManager.Save();
                return "Removed Successfully";
            }
            catch (Exception exception)
            {
                return "Evaluation Incomplete. Error:" + exception;
            }

        }
    }
}

UMS_MVC/Views/Evaluation/Index.cshtml
@model List<UMS_MVC.DataModel.Models.TeacherEvaluation.EvaluationConfiguration>

@{
    Layout = Session["LayoutMgr"].ToString();
    //var config = (ViewBag.config) as EvaluationConfiguration;  
    var x = 1;    
}

<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne" style="background-color: silver">
        <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Evaluation Configuration
            </a>
            <button onclick="editConfig(0)" class="btn btn-danger btn-sm pull-right"><span class="glyphicon glyphicon-plus"></span></button>
        </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne" style="border: 2px solid darkgray">
        <div class="panel-body">
            <div class="col-md-5 pre-scrollable">
                <table class="table table-condensed">
                    <tr style="background-color: silver">
                        <th>
                            Serial
                        </th>
                        <th>Semester</th>
                        <th>Started Date</th>
                        <th>Ending Date</th>
                    </tr>
                    @foreach (var i in Model)
                    {
                        <tr>
                            <td>@x</td>
                            <td>@i.Semester.SemesterNYear</td>
                            <td>@i.StartDate</td>
                            <td>@i.EndDate</td>
                            <td><button onclick="editConfig(@i.EvaluationConfigurationId)" class="btn btn-info btn-sm">Edit</button></td>
                        </tr>
                        x++;
                    }
                </table>
            </div>
            <div class="col-md-7" id="loadConfig">

            </div>
        </div>
    </div>
    <div class="panel-heading" role="tab" id="heading2" style="background-color: silver">
        <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse2" aria-expanded="true" aria-controls="collapse2">
                Data Assessment Manager
            </a>
        </h4>
    </div>
    <div id="collapse2" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading2" style="border: 2px solid darkgray">
        <div class="panel-body">
            <div class="form-group">
                @Html.DropDownList("SemesterId", (SelectList)ViewBag.semesterId, "--Select Semester--", htmlAttributes: new { @class = "form-control" })
                <div id="loadAssessment">

                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">

        $('#SemesterId').change(function() {
            loadAssesment();
        });

        function loadAssesment() {
            var x = document.getElementById("SemesterId").value;
            $.ajax({
                type: 'GET',
                data: { semesterId: x },
                url: '/Evaluation/AssessmentDataPartial',
                success: function (data) {
                    $('#loadAssessment').html(data);
                }
            });
        }
        function loadPage() {
            $.ajax({
                type: 'GET',
                url: '/Evaluation/Index',
                success: function() {
                    window.location.reload(true);
                }
            });
        }

        function editConfig(id) {

            if (id > 0) {
                var url1 = '../Evaluation/ConfigDataPartial';
                $('#loadConfig').load(url1, { id: id });
            } else {
                var url = '../Evaluation/ConfigDataPartial';
                $('#loadConfig').load(url);
            }

        }

        function MsgTiming() {
            loadAssesment();
            $('#removeMsg').fadeIn(500);
            $('#removeMsg').delay(1500).fadeOut(300);
            

        }
    </script>
}

UMS_MVC/Views/Evaluation/_assessmentDataPartial.cshtml
@model List<UMS_MVC.ViewModels.ViewModels.DataAssessmentViewModel>

@{
    var x = 1;
}


<label >List Of Assessment Data's</label>
<label id="removeMsg">

</label>
<div class="pre-scrollable">
    <table class="table table-condensed">
        <tr style="background-color: silver">
            <th>
                Sl.
            </th>
            <th>
                Course Name
            </th>
            <th>Section ID</th>
            <th>
                Semester
            </th>
            <th>Total</th>
            <th>
                Done
            </th>
            <th>
                Not Done Yet
            </th>
            <th>Total Ass</th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @x
                </td>
                <td>
                    @item.CourseName
                </td>
                <td>@item.SectionId</td>
                <td>
                    @item.SemesterName
                </td>
                <td>@item.TotalStudent</td>
                <td>
                    @item.CompletedSurvey
                </td>
                <td>
                    @item.UncompletedSurvey
                </td>
                <td>@item.AssesmentCounter</td>
                <td>
                    @{
                        if (item.UncompletedSurvey == 0 && item.TotalStudent != 0)
                        {
                            @Ajax.ActionLink("Delete", "RemoveAssData", "Evaluation", new { id = item.SectionId }, new AjaxOptions()

                            {
                                HttpMethod = "POST",
                                UpdateTargetId = "removeMsg",
                                InsertionMode = InsertionMode.Replace,
                                Confirm = "Are you sure to remove this row ?",
                                OnComplete = "MsgTiming()"
                            })
                        }
                    }
                </td>
            </tr>
            x++;
        }
    </table>
</div>

UMS_MVC/Views/Evaluation/_configDataPartial.cshtml
@model UMS_MVC.DataModel.Models.TeacherEvaluation.EvaluationConfiguration


<div>
    <label>Edit Here</label>
    @using (Ajax.BeginForm("UpdateEvaluation", "Evaluation", new AjaxOptions()
    {
        HttpMethod = "Post",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "EvaMsg",
        OnComplete = "loadPage()"
    }))
    {
        <div class="form-horizontal">
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.EvaluationConfigurationId)

            <div class="form-group">
                @Html.LabelFor(model => model.SemesterId, "Semester Name", new {@class = "control-label col-md-4"})
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.SemesterId, (SelectList)TempData["semesterId"], htmlAttributes: new {@class = "form-control"})
                    @Html.ValidationMessageFor(model => model.SemesterId)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StartDate, new {@class = "control-label col-md-4"})
                <div class="col-md-8">
                    @Html.TextBoxFor(model => model.StartDate, "{0:yyyy-MM-dd}", new {@type = "date", @class = "form-control"})
                    @Html.ValidationMessageFor(model => model.StartDate)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EndDate, new {@class = "control-label col-md-4"})
                <div class="col-md-8">
                    @Html.TextBoxFor(model => model.EndDate, "{0:yyyy-MM-dd}", new {@type = "date", @class = "form-control"})
                    @Html.ValidationMessageFor(model => model.EndDate)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Remarks, new {@class = "control-label col-md-4"})
                <div class="col-md-8">
                    @Html.TextBoxFor(model => model.Remarks, new {@class = "form-control"})
                    @Html.ValidationMessageFor(model => model.Remarks)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-4 col-md-8">
                    <input type="submit" value="Save" class="btn btn-lg btn-success"/>
                    <h5 style="color: darkgreen" id="EvaMsg"></h5>
                </div>
            </div>
        </div>
    }
</div>