UMS_MVC/Controllers/RoleWiseController/FacultyOrTeacherController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using UMS_MVC.Controllers.OtherSpecialControllers;
using UMS_MVC.DataModel.Connection;
using UMS_MVC.DataModel.Models;
using UMS_MVC.DataModel.Models.Essential_Types;
using UMS_MVC.Manager.DAL.DAO;

namespace UMS_MVC.Controllers.RoleWiseController
{
    public class FacultyOrTeacherController : Controller
    {
        private UmsDbContext db = new UmsDbContext();
        private OtherController otherCtrl=new OtherController();
        private readonly CourseForStudentManger _courseForStudentManger=new CourseForStudentManger();
        private readonly SemesterManager _semesterManager=new SemesterManager();
        private readonly SectionManager _sectionManager=new SectionManager();

        public ActionResult Index()
        {
            if (Session["UserObj"] == null) return RedirectToAction("LogInresultSubmit", "Home");
            var account = (Account)Session["UserObj"];
            if (account.AccountsRole.AccountType != "Admin" && account.AccountsRole.AccountType != "Teacher" && account.AccountsRole.AccountType != "Advisor" && account.AccountsRole.AccountType != "Support") return RedirectToAction("NotPermitted", "Home");

            //////////////// main code start /////////////////////////////
            var findSpecific = otherCtrl.GetTeachers().Where(s => s.LoginId == account.LoginIdentity);
            if (findSpecific.Any())
            {
                var findTeacher = otherCtrl.GetTeachers().Single(s => s.LoginId == account.LoginIdentity);
                //var getTakencourses =_sectionManager.GetAllSections().Where(s => s.TeacherId == findTeacher.TeacherId);
                //ViewData["TakenCourses"] = getTakencourses;
                return View(findTeacher);
            }
            TempData["msgTeacherNotFound"] = "Sorry ! your Teacher Profile may not be created please contact to Software section";
            return RedirectToAction("LogInresultSubmit", "Home");

        }

        public ActionResult SectionIndex(int? SemesterNYear)
        {
            if (Session["UserObj"] == null) return RedirectToAction("LogInresultSubmit", "Home");
            var account = (Account)Session["UserObj"];
            if (account.AccountsRole.AccountType != "Admin" && account.AccountsRole.AccountType != "Teacher" && account.AccountsRole.AccountType != "Advisor" && account.AccountsRole.AccountType != "Support") return RedirectToAction("NotPermitted", "Home");
            //////////////// main code start /////////////////////////////
            
            if (account.AccountsRole.AccountType == "Admin")
            {
                SortSemesterForAdmin(SemesterNYear);
            }
            else
            {
                if (_sectionManager.GetAllSectionForTeachers(account.LoginIdentity).Count > 0)
                {
                    SortSemesterForTeacher(SemesterNYear);
                }
                else
                {
                    TempData["msg"] = "No Section";
                    return RedirectToAction("Index");
                }
                

            }
            return View();
        }

        public void SortSemesterForAdmin(int? SemesterNYear)
        {
            var getAllsectionsCustom = _sectionManager.GetAllSectionsByCourseCodewise();
            var findActiveSemester = _semesterManager.GetActiveSemester();
            if (SemesterNYear > 0)
            {

                TempData["SemesterNYear"] = new SelectList(_semesterManager.GetAllSemester(), "SemesterId", "SemesterNYear", SemesterNYear);
                TempData["Sections"] = new SelectList(getAllsectionsCustom.Where(s => s.SemesterId == SemesterNYear), "SectionId", "SectionName");
            }
            else
            {
                TempData["SemesterNYear"] = new SelectList(_semesterManager.GetAllSemester(), "SemesterId", "SemesterNYear", findActiveSemester.SemesterId);
                TempData["Sections"] = new SelectList(getAllsectionsCustom.Where(s => s.SemesterId == findActiveSemester.SemesterId), "SectionId", "SectionName");
            }
        }

        public void SortSemesterForTeacher(int? SemesterNYear)
        {
            var account = (Account)Session["UserObj"];
            var getSectionByTeacher = _sectionManager.GetAllSectionForTeachers(account.LoginIdentity);
            var selectedSemester = new List<Semester>();
            var findActiveSemester = _semesterManager.GetActiveSemester();
           
            foreach (var section in getSectionByTeacher.DistinctBy(s => s.SemesterId))
            {
                var semester = new Semester { SemesterId = section.SemesterId, SemesterNYear = section.Semester.SemesterNYear, ActiveSemester = section.Semester.ActiveSemester };
                selectedSemester.Add(semester);
            }
            if (SemesterNYear > 0)
            {

                TempData["SemesterNYear"] = new SelectList(selectedSemester, "SemesterId", "SemesterNYear", SemesterNYear);
                TempData["Sections"] = new SelectList(getSectionByTeacher.Where(s => s.SemesterId == SemesterNYear), "SectionId", "SectionName");
            }
            else
            {
                if (getSectionByTeacher.Count(s => s.SemesterId == findActiveSemester.SemesterId) > 0)
                {
                    TempData["SemesterNYear"] = new SelectList(selectedSemester, "SemesterId", "SemesterNYear", findActiveSemester.SemesterId);
                    TempData["Sections"] = new SelectList(getSectionByTeacher.Where(s => s.SemesterId == findActiveSemester.SemesterId), "SectionId", "SectionName");
                }
                var getLastSemeserHeattented = getSectionByTeacher.OrderByDescending(s=>s.SemesterId).First().SemesterId;
                TempData["SemesterNYear"] = new SelectList(selectedSemester, "SemesterId", "SemesterNYear", getLastSemeserHeattented);
                TempData["Sections"] = new SelectList(getSectionByTeacher.Where(s => s.SemesterId == getLastSemeserHeattented), "SectionId", "SectionName");
            }
        }

        public string GradeUplodadNotification()
        {
            var semesterInfo = _semesterManager.GetActiveSemester();
            var finalNotification = "deactivated.";
            if (semesterInfo.MidTerm)
            {
                finalNotification = "activated for Mid Term, " + semesterInfo.SemesterNYear + ".";
            }
            if (semesterInfo.FinalTerm)
            {
                finalNotification = "activated for FinalTerm, " + semesterInfo.SemesterNYear + ".";
            }
            return finalNotification;
        }

        public PartialViewResult StudentListBySection(int sectionId=0)
        {
            var account = (Account) Session["UserObj"];
            var getStudentListBySection = _courseForStudentManger.GetAllCourseForStudentsAcademicsBysection(sectionId);
            return PartialView("_redirectToPortalNotifiy");
           // ViewBag.gradeuploadNoti = GradeUplodadNotification();
            //if (account.AccountsRole.AccountType == "Admin")
            //{
            //    return PartialView("_StudentListOfaSectionDefault", getStudentListBySection);
            //}
            //if (CheckTeacherWiseSection(sectionId, account.LoginIdentity))
            //{
            //    var getCourseType = _sectionManager.GetSingleSection(sectionId).CourseForDepartment.CourseType.ToUpper();
            //    //var getCourseType = getStudentListBySection.First().CourseForDepartment.CourseType;
            //    if (getCourseType == "LAB")
            //    {
            //        return PartialView("_studentListOfaSectionLab", getStudentListBySection);
            //    }
            //    if (getCourseType == "OTHER")
            //    {
            //        return PartialView("_studentListOfSectionOther", getStudentListBySection);
            //    }
            //    else
            //    {
            //        return PartialView("_StudentListOfaSectionDefault", getStudentListBySection);
            //    }
                
            //}
            //var demoData = new List<CourseForStudentsAcademic>();
            //return PartialView("_StudentListOfaSectionDefault",demoData);
        }

        public ActionResult GradeUpload(int sectionId=0)
        {
            if (Session["UserObj"] == null) return RedirectToAction("LogInresultSubmit", "Home");
            var account = (Account)Session["UserObj"];
           // if (account.AccountsRole.AccountType != "Admin" && account.AccountsRole.AccountType != "Teacher" && account.AccountsRole.AccountType != "Advisor" && account.AccountsRole.AccountType != "ExamCtrl") return RedirectToAction("NotPermitted", "Home");
            if (account.AccountsRole.AccountType != "Admin" ) return RedirectToAction("NotPermitted", "Home");
            //...Main Code
           
            if (sectionId > 0)
            {
                TempData["sectionId"] = sectionId;
                var studentList =
                    _courseForStudentManger.GetAllCourseForStudentsAcademicsBysection(sectionId);

                if (account.AccountsRole.AccountType == "Admin")
                {
                    GetAccessForAdmins(sectionId);
                    return View(studentList.ToList());
                }
                if (account.AccountsRole.AccountType == "ExamCtrl")
                {
                    GetAccessForExamController(sectionId);
                    return View(studentList.ToList());
                }
                if (account.AccountsRole.AccountType == "Teacher" || account.AccountsRole.AccountType == "Advisor")
                {
                    if (AccessToHighLightedSection(sectionId))
                    {
                        if (CheckTeacherWiseSection(sectionId, account.LoginIdentity))
                        {

UMS_MVC/Views/FacultyOrTeacher/LoadStudentresultView.cshtml
@model UMS_MVC.DataModel.Models.Essential_Types.CourseForStudentsAcademic

@{
    Layout = null;
}
@{
    if (TempData["gradeUploadMsg"]!=null)
    {
  <label>@TempData["gradeUploadMsg"]</label>
    }
}
@using (Html.BeginForm("SubmitGrade","FacultyOrTeacher"))
{
    @Html.HiddenFor(model => Model.CourseForStudentsAcademicId)
    <tr>
        <td>
            
            @Html.DisplayFor(model => Model.StudentIdentification.StudentId)
        </td>
        <td>
            @Html.DisplayFor(model => Model.StudentIdentification.StudentInfo.StudentName)
        </td>
        <td>
            @Html.TextBoxFor(model => Model.Attendance, new { @class = "form-control input-smCustom3ForGrade" })
        </td>
        <td>
            @Html.TextBoxFor(model => Model.ClassTest, new { @class = "form-control input-smCustom3ForGrade" })
        </td>
        <td>
            @Html.TextBoxFor(model => Model.Midterm, new { @class = "form-control input-smCustom3ForGrade" })

        </td>
        <td>
            @Html.TextBoxFor(model => Model.FinalTerm, new { @class = "form-control input-smCustom3ForGrade" })
        </td>
        <td>
            @Html.DisplayFor(model => Model.TotalMark)
        </td>
        <td>
            @Html.DisplayFor(model => Model.Grade)
        </td>
        <td>
            @Html.DisplayFor(model => Model.LetterGrade)
        </td>
        <td>
            <input type="submit" value="Submit"  /><div id="loadF2"></div>
        </td>
    </tr>
}
    @*<script type="text/javascript">
        function submitResult() {
            
            var courseForStudentId = new String(@ViewBag.courseid);
            var attendance = parseFloat((document.getElementById("Attendance")).value);
            var classTest = parseFloat((document.getElementById("ClassTest")).value);
            var midterm = parseFloat((document.getElementById("Midterm")).value);
            var finalTerm = parseFloat((document.getElementById("FinalTerm")).value);
            $('#loadF2').load('@Url.Action("SubmitGrade")', {
                courseId: courseForStudentId, attendance: attendance, classTest: classTest, midterm: midterm, finalTerm: finalTerm
            });
            courseForStudentId = 0.0;
            attendance = 0.0;
            classTest = 0.0;
            midterm = 0.0;
            finalTerm = 0.0;
        }

    </script>*@

UMS_MVC/Views/FacultyOrTeacher/SectionIndex.cshtml
@{
    ViewBag.Title = "SectionIndex";
    Layout = Session["LayoutMgr"].ToString();

    var semesterObj = ViewBag.semesterInfo;
}
<h3 style="color: crimson">Section Index</h3>
<div class="panel panel-default">
    <div class="panel-heading">  
        <div class="form-inline">
            @using (Html.BeginForm())
            {
                <div class="form-group">@Html.DropDownList("SemesterNYear", (SelectList)TempData["SemesterNYear"],new{@class="form-control"})</div>
                <div class="form-group">@Html.DropDownList("Sections", (SelectList)TempData["Sections"],"",new{@class="form-control"})</div>
                <input type="submit" class="hidden"/>
            }
            
        </div>
    </div>
    <div id="LoadStudentBySection" class="panel panel-body">
        
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        
        $("#SemesterNYear").change(function () {
            $("input[type=submit]").click();
        });

        $('#Sections').change(function () {
            var id = $('#Sections :selected').val();
            $('#LoadStudentBySection').load('@Url.Action("StudentListBySection","FacultyOrTeacher")', { sectionId: id });
        });

    </script>
}

UMS_MVC/Views/FacultyOrTeacher/_FinalGradeUpload.cshtml
@model UMS_MVC.DataModel.Models.Essential_Types.CourseForStudentsAcademic

@{
    Layout = null;
}

@using (Html.BeginForm("SubmitGrade", "FacultyOrTeacher"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => Model.CourseForStudentsAcademicId)
    @Html.HiddenFor(model => Model.Midterm)
    <tr>
        <td>

            @Html.DisplayFor(model => Model.StudentIdentification.StudentId)
        </td>
        <td>
            @Html.DisplayFor(model => Model.StudentIdentification.StudentInfo.StudentName)
        </td>
        <td>
            @Html.TextBoxFor(model => Model.Attendance, new { @class = "form-control input-smCustom3ForGrade" })
        </td>
        <td>
            @Html.TextBoxFor(model => Model.ClassTest, new { @class = "form-control input-smCustom3ForGrade" })
        </td>
        <td>
            @Html.DisplayFor(model => Model.Midterm)
        </td>
        <td>
            @Html.TextBoxFor(model => Model.FinalTerm, new { @class = "form-control input-smCustom3ForGrade" })
        </td>
        <td>
            <b>@Html.DisplayFor(model => Model.TotalMark)</b>
        </td>
        <td style="font-size: 14px">
            <b>@Html.DisplayFor(model => Model.Grade)</b>
        </td>
        <td style="font-size: 14px">
            <b>@Html.DisplayFor(model => Model.LetterGrade)</b>
        </td>
        <td>
            <input type="submit" value="Submit" class="btn btn-sm btn-default" />
        </td>
        <td>
            <div id="loadF2">
                @if (TempData["gradeUploadMsg"] != null)
                {
                    if (TempData["gradeForCourseId"].ToString() == Model.CourseForStudentsAcademicId.ToString() && TempData["gradeUploadMsg"].ToString() == "1")
                    {
                        <span class="glyphicon glyphicon-saved" style="font-size: 15px;color: green"></span>
                    }
                    else if (TempData["gradeForCourseId"].ToString() == Model.CourseForStudentsAcademicId.ToString() && TempData["gradeUploadMsg"].ToString() == "2")
                    {
                        <span class="glyphicon glyphicon-ban-circle" style="font-size: 15px;color: orangered"></span>
                    }
                }
            </div>

        </td>
    </tr>
}

UMS_MVC/Views/FacultyOrTeacher/_LabAdminGradeUpload.cshtml
@model UMS_MVC.DataModel.Models.Essential_Types.CourseForStudentsAcademic

@{
    Layout = null;
}

@using (Html.BeginForm("SubmitGradeForLab", "FacultyOrTeacher"))
{

    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => Model.CourseForStudentsAcademicId)
    <tr>
        <td>
           StudentId
        </td>
        <td>
           StudentName
        </td>
        <td>
            ---
        </td>
        <td>
            ---
        </td>
        <td>
            @Html.TextBoxFor(model => Model.Midterm, new { @class = "form-control input-smCustom3ForGrade" })
        </td>
        <td>
            @Html.TextBoxFor(model => Model.FinalTerm, new { @class = "form-control input-smCustom3ForGrade" })
        </td>
        <td>
            <b>@Html.DisplayFor(model => Model.TotalMark)</b>
        </td>
        <td style="font-size: 14px">
            <b>@Html.DisplayFor(model => Model.Grade)</b>
        </td>
        <td style="font-size: 14px">
            <b>@Html.DisplayFor(model => Model.LetterGrade)</b>
        </td>
        <td>
            <input type="submit" value="Submit" class="btn btn-sm btn-default" />
        </td>
        <td>
            <div id="loadF2">
                @if (TempData["gradeUploadMsg"] != null)
                {
                    if (TempData["gradeForCourseId"].ToString() == Model.CourseForStudentsAcademicId.ToString() && TempData["gradeUploadMsg"].ToString() == "1")
                    {
                        <span class="glyphicon glyphicon-saved" style="font-size: 15px;color: green"></span>
                    }
                    else if (TempData["gradeForCourseId"].ToString() == Model.CourseForStudentsAcademicId.ToString() && TempData["gradeUploadMsg"].ToString() == "2")
                    {
                        <span class="glyphicon glyphicon-ban-circle" style="font-size: 15px;color: orangered"></span>
                    }
                }
            </div>

        </td>
    </tr>

}

UMS_MVC/Views/FacultyOrTeacher/_LabFinalGradeUpload.cshtml
@model UMS_MVC.DataModel.Models.CourseForStudentsAcademic

@{
    Layout = null;
}

@using (Html.BeginForm("SubmitGradeForLab", "FacultyOrTeacher"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => Model.CourseForStudentsAcademicId)
    @Html.HiddenFor(model => Model.Midterm)
    <tr>
        <td>

            @Html.DisplayFor(model => Model.StudentIdentification.StudentId)
        </td>
        <td>
            @Html.DisplayFor(model => Model.StudentIdentification.StudentInfo.StudentName)
        </td>
        <td>
            ---
        </td>
        <td>
            ---
        </td>
        <td>
            @Html.DisplayFor(model => Model.Midterm)
        </td>
        <td>
            @Html.TextBoxFor(model => Model.FinalTerm, new { @class = "form-control input-smCustom3ForGrade" })
        </td>
        <td>
            <b>@Html.DisplayFor(model => Model.TotalMark)</b>
        </td>
        <td style="font-size: 14px">
            <b>@Html.DisplayFor(model => Model.Grade)</b>
        </td>
        <td style="font-size: 14px">
            <b>@Html.DisplayFor(model => Model.LetterGrade)</b>
        </td>
        <td>
            <input type="submit" value="Submit" class="btn btn-sm btn-default" />
        </td>
        <td>
            <div id="loadF2">
                @if (TempData["gradeUploadMsg"] != null)
                {
                    if (TempData["gradeForCourseId"].ToString() == Model.CourseForStudentsAcademicId.ToString() && TempData["gradeUploadMsg"].ToString() == "1")
                    {
                        <span class="glyphicon glyphicon-saved" style="font-size: 15px;color: green"></span>
                    }
                    else if (TempData["gradeForCourseId"].ToString() == Model.CourseForStudentsAcademicId.ToString() && TempData["gradeUploadMsg"].ToString() == "2")
                    {
                        <span class="glyphicon glyphicon-ban-circle" style="font-size: 15px;color: orangered"></span>
                    }
                }
            </div>

        </td>
    </tr>
}

UMS_MVC/Views/FacultyOrTeacher/_LabHeading.cshtml
<tr style="background-color: seagreen;color: white">
    <th>
       Student Id
    </th>
    <th>
        Student Name
    </th>

    <th>
       ---
    </th>
    <th>
      ---
    </th>
    <th>
        Midterm (100)
    </th>
    <th>
       FinalTerm (100)
    </th>
    <th>
        Total Mark
    </th>
    <th>
        Grade
    </th>
    <th>
       LetterGrade
    </th>
    <th>

    </th>
    <th>
        ------
    </th>
</tr>

UMS_MVC/Views/FacultyOrTeacher/_OtherFinalGradeUpload.cshtml
@model UMS_MVC.DataModel.Models.Essential_Types.CourseForStudentsAcademic

@{
    Layout = null;
}

@using (Html.BeginForm("SubmitGradeForOther", "FacultyOrTeacher"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => Model.CourseForStudentsAcademicId)
    @Html.HiddenFor(model => Model.Midterm)
    <tr>
        <td>

            @Html.DisplayFor(model => Model.StudentIdentification.StudentId)
        </td>
        <td>
            @Html.DisplayFor(model => Model.StudentIdentification.StudentInfo.StudentName)
        </td>
        <td>
            ---
        </td>
        <td>
            ---
        </td>
        <td>
            ---
        </td>
        <td>
            @Html.TextBoxFor(model => Model.FinalTerm, new { @class = "form-control input-smCustom3ForGrade" })
        </td>
        <td>
            <b>@Html.DisplayFor(model => Model.TotalMark)</b>
        </td>
        <td style="font-size: 14px">
            <b>@Html.DisplayFor(model => Model.Grade)</b>
        </td>
        <td style="font-size: 14px">
            <b>@Html.DisplayFor(model => Model.LetterGrade)</b>
        </td>
        <td>
            <input type="submit" value="Submit" class="btn btn-sm btn-default" />
        </td>
        <td>
            <div id="loadF2">
                @if (TempData["gradeUploadMsg"] != null)
                {
                    if (TempData["gradeForCourseId"].ToString() == Model.CourseForStudentsAcademicId.ToString() && TempData["gradeUploadMsg"].ToString() == "1")
                    {
                        <span class="glyphicon glyphicon-saved" style="font-size: 15px;color: green"></span>
                    }
                    else if (TempData["gradeForCourseId"].ToString() == Model.CourseForStudentsAcademicId.ToString() && TempData["gradeUploadMsg"].ToString() == "2")
                    {
                        <span class="glyphicon glyphicon-ban-circle" style="font-size: 15px;color: orangered"></span>
                    }
                }
            </div>

        </td>
    </tr>
}

UMS_MVC/Views/FacultyOrTeacher/_OtherMidGradeUpload.cshtml
@model UMS_MVC.DataModel.Models.Essential_Types.CourseForStudentsAcademic

@{
    Layout = null;
}

@using (Html.BeginForm("SubmitGradeForOther", "FacultyOrTeacher"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => Model.CourseForStudentsAcademicId)
    <tr>
        <td>

            @Html.DisplayFor(model => Model.StudentIdentification.StudentId)
        </td>
        <td>
            @Html.DisplayFor(model => Model.StudentIdentification.StudentInfo.StudentName)
        </td>
        <td>
            ---
        </td>
        <td>
            ---
        </td>
        <td>
            ---
        </td>
       <td>
            @Html.DisplayFor(model => Model.FinalTerm)
        </td>
        <td>
            <b>@Html.DisplayFor(model => Model.TotalMark)</b>
        </td>
        <td style="font-size: 14px">
            <b>@Html.DisplayFor(model => Model.Grade)</b>
        </td>
        <td style="font-size: 14px">
            <b>@Html.DisplayFor(model => Model.LetterGrade)</b>
        </td>
        <td>
            <input type="submit" value="Submit" class="btn btn-sm btn-default" />
        </td>
        <td>
            <div id="loadF2">
                @if (TempData["gradeUploadMsg"] != null)
                {
                    if (TempData["gradeForCourseId"].ToString() == Model.CourseForStudentsAcademicId.ToString() && TempData["gradeUploadMsg"].ToString() == "1")
                    {
                        <span class="glyphicon glyphicon-saved" style="font-size: 15px;color: green"></span>
                    }
                    else if (TempData["gradeForCourseId"].ToString() == Model.CourseForStudentsAcademicId.ToString() && TempData["gradeUploadMsg"].ToString() == "2")
                    {
                        <span class="glyphicon glyphicon-ban-circle" style="font-size: 15px;color: orangered"></span>
                    }
                }
            </div>

        </td>
    </tr>
}

UMS_MVC/Views/FacultyOrTeacher/_UniHeading.cshtml
<tr style="background-color: seagreen;color: white">
    <th>
        Student Id
    </th>
    <th>
        Student Name
    </th>

    <th>
        Attendance (10)
    </th>
    <th>
        ClassTest (50)
    </th>
    <th>
        Midterm (100)
    </th>
    <th>
        FinalTerm (100)
    </th>
    <th>
        Total Mark
    </th>
    <th>
        Grade
    </th>
    <th>
        LetterGrade
    </th>
    <th>

    </th>
    <th>
        ------
    </th>
</tr>

UMS_MVC/Views/FacultyOrTeacher/_redirectToPortalNotifiy.cshtml
<div class="alert alert-warning alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <label><span class="glyphicon glyphicon-exclamation-sign"></span>Section index, Marks Upload, Note Upload is currently fully moved to portal. <a href="http://www.primeasia-ums.com"><i style="color: #090039;font-weight: bold" class="fa fa-gg"></i> UMS Portal Login</a> </label>
</div>