UMS_MVC/Controllers/AdminMatter/GradingSystemController.cs
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web.Mvc;
using UMS_MVC.DataModel.Models;
using UMS_MVC.DataModel.Models.Essential_Types;
using UMS_MVC.Manager.DAL.DAO;

namespace UMS_MVC.Controllers.AdminMatter
{
    public class GradingSystemController : Controller
    {
        private readonly GradingSystemManager _gradingSystemManager;

        public GradingSystemController()
        {
            _gradingSystemManager=new GradingSystemManager();
        }
        public PartialViewResult GradingSystemIndexPartial()
        {
            if (Session["UserObj"] == null)
            {
                ViewBag.msg = "You are Not logged in.";
                return PartialView("_GradingSystemPartial");
            }
            if (Session["specialPower"] == null)
            {
                ViewBag.msg = "Access Denied";
                return PartialView("_GradingSystemPartial");
            }
            return PartialView("_GradingSystemPartial", _gradingSystemManager.GetAllGradingSystems().ToList());
        }
        public PartialViewResult EditGradingSystemPartial(int id)
        {
            if (Session["UserObj"] == null)
            {
                ViewBag.msg = "You are Not logged in.";
                return PartialView("_GradingSystemPartial");
            }
            if (Session["specialPower"] == null)
            {
                ViewBag.msg = "Access Denied";
                return PartialView("_GradingSystemPartial");
            }
            var aGradingSystem=new GradingSystem();
            if (id > 0)
            {
                aGradingSystem = _gradingSystemManager.FindGradingSystem(id);
            }
           
            return PartialView("_EditGradingSystemPartial", aGradingSystem);
        }
        public string UpdateGradingSystemCommit(GradingSystem gradingSystem, string save)
        {
            string msg = "";
            try
            {
                if (ModelState.IsValid)
                {
                    switch (save)
                    {
                        case "Add":
                           _gradingSystemManager.Insert(gradingSystem);
                            
                            msg = "Insert Completed";
                            break;
                        case "Update":
                            _gradingSystemManager.Update(gradingSystem);
                            msg = "Update Completed";
                            break;
                        case "Delete":
                            _gradingSystemManager.Delete(gradingSystem.GradingSystemId);
                            msg = "Delete Completed";
                            break;
                    }
                    _gradingSystemManager.Save();
                }
                else
                {
                    msg = "Update Failed";
                }
            }
            catch (DbUpdateException)
            {

                msg = "Internal Entity exception occured.";
            }

            return msg;
        }
    }
}

UMS_MVC/Views/GradingSystem/_EditGradingSystemPartial.cshtml
@model UMS_MVC.DataModel.Models.Essential_Types.GradingSystem

@using (Ajax.BeginForm("UpdateGradingSystemCommit", "GradingSystem", new AjaxOptions()
{
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "msgFomServer",
    OnComplete = "dismiss_Modal"
}))
{
    @Html.AntiForgeryToken()

    <div>
        <h4>Power Work Access</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(model => model.GradingSystemId)
        <table class="table table-hover">
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.GradingSystemName, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.GradingSystemName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.GradingSystemName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                   
                </td>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.GradingCode, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.GradingCode, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.GradingCode, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Attendance, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.Attendance, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Attendance, "", new { @class = "text-danger" })
                        </div>
                    </div></td>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.AttendancePercent, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                           @Html.EditorFor(model => model.AttendancePercent, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.AttendancePercent, "", new { @class = "text-danger" })
                           
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.ClassTest, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.ClassTest, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ClassTest, "", new { @class = "text-danger" })

                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.ClassTestPercent, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.ClassTestPercent, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ClassTestPercent, "", new { @class = "text-danger" })

                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.MidTerm, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.MidTerm, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MidTerm, "", new { @class = "text-danger" })

                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.MidTermPercent, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.MidTermPercent, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MidTermPercent, "", new { @class = "text-danger" })

                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.FinalTerm, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.FinalTerm, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FinalTerm, "", new { @class = "text-danger" })

                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.FinalTermPercent, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                           @Html.EditorFor(model => model.FinalTermPercent, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.FinalTermPercent, "", new { @class = "text-danger" })
                           </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td></td>
                <td></td>
            </tr>
        </table>
        <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" name="save" class="btn btn-success btn-group"/>
                <input type="submit" value="Update" name="save" class="btn btn-warning btn-group"/>
                <input type="submit" value="Delete" name="save" class="btn btn-danger btn-group"/>
            </div>

        <br/>
        <br />
        <div id="alertDivHighLight" style="display: none" class="alert alert-success" role="alert"> <label style="color: darkgreen" id="msgFomServer"></label> <span class="glyphicon glyphicon-ok"></span></div>

    </div>
}

UMS_MVC/Views/GradingSystem/_GradingSystemPartial.cshtml
@model List<UMS_MVC.DataModel.Models.Essential_Types.GradingSystem>

<h4 style="color: #008080">
    Grading Systems</h4>

    @{
        if (ViewBag.msg != null)
        {
            <h3 style="color: orangered">@ViewBag.msg</h3>
        }
        else
        {
            <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#adminMainModal" onclick="loadGradingSystemEdit(0)">
                <span style="color: green" class="glyphicon glyphicon-plus"></span> Add New
            </button>
            <table class="table  table-condensed" style="font-size: 12px;">
                <tr style="font-weight: bold">
                    <td>GID</td>
                    <td>Gr Code</td>
                    <td>Gr Sys Name</td>
                    <td>Att</td>
                    <td>CT</td>
                    <td>Mid</td>
                    <td>Final</td>
                    @*<td>Att(%)</td>
                    <td>CT(%)</td>
                    <td>Mid(%)</td>
                    <td>Final(%)</td>*@
                    <td>Options</td>
                </tr>

                @{
                    if (Model != null)
                    {
                        foreach (var gs in Model)
                        {
                            <tr>
                                <td>@gs.GradingSystemId</td>
                                <td>@gs.GradingCode</td>
                                <td>@gs.GradingSystemName</td>
                                <td>@gs.Attendance</td>
                                <td>@gs.ClassTest</td>
                                <td>@gs.MidTerm</td>
                                <td>@gs.FinalTerm</td>
                                <td>
                                    <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#adminMainModal" onclick="loadGradingSystemEdit('@gs.GradingSystemId')">
                                        <span style="color: green" class="glyphicon glyphicon-pencil"></span>
                                    </button>
                                </td>
                            </tr>
                            <tr style="color: crimson; background-color: gainsboro; font-weight: bold">
                                <td></td>
                                <td></td>
                                <td style="text-align: right">Percent :</td>
                                <td>@gs.AttendancePercent%</td>
                                <td>@gs.ClassTestPercent%</td>
                                <td>@gs.MidTermPercent%</td>
                                <td>@gs.FinalTermPercent%</td>
                                <td>

                                </td>
                            </tr>

                        }
                    }
                }
            </table>
        }
    }