UMS_MVC/Controllers/OtherSpecialControllers/StudentMasterController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using UMS_MVC.DataModel.Connection;
using UMS_MVC.DataModel.Models;
using UMS_MVC.DataModel.Models.Essential_Types;
using UMS_MVC.Manager.DAL.DAO;
using UMS_MVC.Manager.DAL.DAO.Intefaces;
using UMS_MVC.Manager.DAL.DAO.Repository;
using UMS_MVC.ViewModels.ViewModels;

namespace UMS_MVC.Controllers.OtherSpecialControllers
{
    public class StudentMasterController : Controller
    {
        private readonly UmsDbContext db;
        private readonly StudentManager _studentManager;
        private readonly CourseForStudentManger _courseForStudentManger;
        private readonly PaymentManager _paymentManager;
        private readonly RebateManager _rebateManager;
        private readonly SemesterManager _semesterManager;
        private readonly DepartmentManager _departmentManager;
        private readonly GradeManager _gradeManager;
        private readonly ICourseForStudentRepository _courseForStudentRepository;

        public StudentMasterController()
        {
            db = new UmsDbContext();
            _studentManager = new StudentManager();
            _courseForStudentManger = new CourseForStudentManger();
            _paymentManager = new PaymentManager();
            _rebateManager = new RebateManager();
            _semesterManager = new SemesterManager();
            _departmentManager = new DepartmentManager();
            _gradeManager = new GradeManager();
            _courseForStudentRepository = new CourseForStudentRepository();


        }

        public ActionResult StudentMastersControllers(string searchstudentId)
        {
            if (Session["UserObj"] == null)
                return RedirectToAction("LogInresultSubmit", "Home");
            var account = (Account)Session["UserObj"];
            if (account.AccountsRole.AccountType != "Admin") return RedirectToAction("NotPermitted", "Home");
            if (!string.IsNullOrEmpty(searchstudentId))
            {
                var studentIdentity =
                    _studentManager.GetAllStudentIdentifications().FirstOrDefault(s => s.StudentId == searchstudentId);
                if (studentIdentity != null)
                {
                    var studentPaymetRegis =
                       _paymentManager.GetAllPaymentRegistration()
                           .Where(s => s.StudentIdentification.StudentId == searchstudentId);
                    var studentPayment = _paymentManager.GetAllPayments()
                        .Where(s => s.PaymentRegistration.StudentIdentification.StudentId == searchstudentId);
                    var registeredCourses = _courseForStudentManger.GetAllCourseForStudentsAcademics()
                        .Where(s => s.StudentIdentification.StudentId == searchstudentId);
                    var rebateSearch =
                        _rebateManager.GetAllRebate()
                            .Where(s => s.StudentIdentificationId == studentIdentity.StudentIdentificationId);
                    ViewData["StudentIdentity"] = studentIdentity;
                    if (studentPaymetRegis.Any())
                    {
                        ViewData["studentPaymetRegis"] = studentPaymetRegis;
                    }
                    if (studentPayment.Any())
                    {
                        ViewData["StudentPayment"] = studentPayment;
                    }
                    if (rebateSearch.Any())
                    {
                        ViewData["rebate"] = rebateSearch;
                    }
                    if (registeredCourses.Any())
                    {
                        ViewData["registeredCourses"] = registeredCourses;
                    }
                }
                var studentInfo = _studentManager.GetAllStudentInfos().Where(s => s.StudentId == searchstudentId);
                var studentAcademic =
                    _studentManager.GetAllAcademicInfos().Where(s => s.StudentId == searchstudentId);
                var studentDocument =
                    _studentManager.GetAllStudentDocument().Where(s => s.StudentId == searchstudentId);

                if (studentInfo.Any())
                {
                    ViewData["StudentInfo"] = studentInfo.First();
                }
                if (studentAcademic.Any())
                {
                    ViewData["StudentAcademic"] = studentAcademic;
                }
                if (studentDocument.Any())
                {
                    ViewData["StudentDocument"] = studentDocument.First();
                }

            }
            ViewBag.StudentId = searchstudentId;



            return View();
        }
        public ActionResult DeleteStudentIdentity(int? studentidentityId, string searchsVal)
        {
            if (Session["UserObj"] == null)
                return RedirectToAction("LogInresultSubmit", "Home");
            var account = (Account)Session["UserObj"];
            if (account.AccountsRole.AccountType != "Admin") return RedirectToAction("NotPermitted", "Home");
            if (studentidentityId > 0)
            {
                var findStudentIdentity = db.StudentIdentifications.Find(studentidentityId);
                db.StudentIdentifications.Remove(findStudentIdentity);
                db.SaveChanges();
            }
            return RedirectToAction("StudentMastersControllers", new { searchstudentId = searchsVal });
        }
        public ActionResult DeleteStudentInformation(int? sudentIanfoId, string searchsVal)
        {
            var findStudent = db.StudentInfos.Find(sudentIanfoId);
            if (findStudent != null)
            {
                db.StudentInfos.Remove(findStudent);
                db.SaveChanges();
            }
            return RedirectToAction("StudentMastersControllers", new { searchstudentId = searchsVal });
        }
        public ActionResult DeleteStudentAcademic(string searchsVal, string studentId = "")
        {
            if (Session["UserObj"] == null)
                return RedirectToAction("LogInresultSubmit", "Home");
            var account = (Account)Session["UserObj"];
            if (account.AccountsRole.AccountType != "Admin") return RedirectToAction("NotPermitted", "Home");
            var findStudent = db.StudentAcademicInfos.Where(s => s.StudentId == studentId);
            if (findStudent.Any())
            {
                foreach (var studentAcademicInfo in findStudent)
                {
                    db.StudentAcademicInfos.Remove(studentAcademicInfo);
                }
                db.SaveChanges();
            }
            return RedirectToAction("StudentMastersControllers", new { searchstudentId = searchsVal });
        }
        public ActionResult DeleteStudentDocument(int? documentId, string searchsVal)
        {
            if (Session["UserObj"] == null)
                return RedirectToAction("LogInresultSubmit", "Home");
            var account = (Account)Session["UserObj"];
            if (account.AccountsRole.AccountType != "Admin") return RedirectToAction("NotPermitted", "Home");
            if (documentId > 0)
            {
                var findStudent = db.DocumentsaddAddings.Find(documentId);
                db.DocumentsaddAddings.Remove(findStudent);
                db.SaveChanges();
            }
            return RedirectToAction("StudentMastersControllers", new { searchstudentId = searchsVal });
        }
        public ActionResult DeletePaymentRegis(int? studentId, string searchsVal)
        {
            if (Session["UserObj"] == null)
                return RedirectToAction("LogInresultSubmit", "Home");
            var account = (Account)Session["UserObj"];
            if (account.AccountsRole.AccountType != "Admin") return RedirectToAction("NotPermitted", "Home");
            var findPayemtnRegis = db.PaymentRegistrations.Where(s => s.StudentIdentificationId == studentId);
            var findPayments = db.Payments;
            if (findPayemtnRegis.Any())
            {
                foreach (var paymentRegistration in findPayemtnRegis)
                {
                    PaymentRegistration registration = paymentRegistration;
                    foreach (var findPayment in findPayments.Where(s => s.PaymentRegistrationId == registration.PaymentRegistrationId))
                    {
                        db.Payments.Remove(findPayment);

                    }
                    db.SaveChanges();
                    db.PaymentRegistrations.Remove(paymentRegistration);
                }
                db.SaveChanges();
            }
            return RedirectToAction("StudentMastersControllers", new { searchstudentId = searchsVal });
        }
        public ActionResult DeleteRebates(int? studentId, string searchsVal)
        {
            if (Session["UserObj"] == null)
                return RedirectToAction("LogInresultSubmit", "Home");
            var account = (Account)Session["UserObj"];
            if (account.AccountsRole.AccountType != "Admin") return RedirectToAction("NotPermitted", "Home");

            var findPayemtnRegis = db.Rebates.Where(s => s.StudentIdentificationId == studentId);
            if (findPayemtnRegis.Any())
            {
                foreach (var rebates in findPayemtnRegis)
                {
                    db.Rebates.Remove(rebates);
                }
                db.SaveChanges();
            }
            return RedirectToAction("StudentMastersControllers", new { searchstudentId = searchsVal });
        }
        public ActionResult DeleteRegisteredCourses(int? studentId, string searchsVal)
        {
            if (Session["UserObj"] == null)
                return RedirectToAction("LogInresultSubmit", "Home");
            var account = (Account)Session["UserObj"];
            if (account.AccountsRole.AccountType != "Admin") return RedirectToAction("NotPermitted", "Home");

UMS_MVC/Views/StudentMaster/AllDetailsOfSemester.cshtml
@model List<UMS_MVC.DataModel.Models.Essential_Types.CourseForStudentsAcademic>

@{
    //Layout = Session["LayoutMgr"].ToString();
    ViewBag.Title = "Grade report by semester";
    var studentIdenId = ViewBag.sIId;
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@{
    if (Model != null)
    {
        <div>
            <div>
                <div>
                    <h4 style="color: #008b8b; font-weight: bold"><u>Grade Report By Semester</u></h4>
                </div>
                <div>
                    @{
                        double cgpaCal = 0.0,totalCredit=0.0,totalGrade=0.0;
                        foreach (var item2 in Model.Select(a => a.Semester.SemesterNYear).Distinct())
                        {
                            var sem = item2;
                            @*<button class="btn btn-danger btn-sm" onclick="location.href = '@Url.Action("SemesterWiseGrade", "DocumentPrint", new {studenIdenId = studentIdenId, semesterName = sem})';return false; "><span class=" glyphicon glyphicon-print"></span></button>*@
                            var x = 0.0;
                            var y = 0.0;
                            var z = 0.0;
                            var earnedCredit = 0.0;
                            var takenCredits = 0.0;
                            <br />
                            <label style="color: #008b8b">@item2</label>
                            <table class="table table-condensed" style="font-size: 11px">
                                <tr style="background: #008b8b; color: white">
                                    <th width="10%">Course Code </th>
                                    <th width="30%">Course Name </th>
                                    <th width="5%">Credits </th>
                                   
                                    <th width="5%">Mid</th>
                                    <th width="5%">Final</th>
                                    <th width="5%">Grade</th>
                                    <th width="5%">GP</th>
                                    <th width="10%">TGP</th>
                                    <th width="5%">ECR</th>
                                    <th width="5%">SGPA</th>
                                    <th width="5%">CGPA</th>
                                    <td width="5%">Status</td>
                                    <td width="5%">SecId</td>
                                    <th></th>
                                </tr>
                                @foreach (var item in Model.Where(s => s.Semester.SemesterNYear.Equals(item2)))
                                {
                                    var creditVal=item.CourseForDepartment.Credit;
                                    takenCredits += creditVal;
                                    if (item.CourseStatusId == 2)
                                    {
                                        x = x + creditVal;
                                        y = y + item.TotalGrade;
                                        if (item.LetterGrade!="F")
                                        {
                                            earnedCredit += creditVal;
                                        }

                                    }
                                    else
                                    {
                                        x = x + 0;
                                        y = y + 0;
                                    }
                                    <tr>
                                        <td width="10%">@item.CourseForDepartment.CourseCode</td>
                                        <td width="30%">@item.CourseForDepartment.CourseName</td>
                                        @{
                                            if (item.CourseStatusId != 2)
                                            {
                                                <td width="5%">(0.0)</td>
                                            }
                                            else
                                            {
                                                <td width="5%">@creditVal.ToString("0.0")</td>
                                            }
                                        }
                                        
                                        <td width="5%">@item.Midterm</td>
                                        <td width="5%">@item.FinalTerm</td>
                                        <td width="5%">@item.LetterGrade</td>
                                        <td width="5%">@item.Grade.ToString("0.00")</td>
                                        <td width="10%">@item.TotalGrade</td>
                                        <th width="5%"></th>
                                        <th width="5%"></th>
                                        <th width="5%"></th>
                                        <td width="5%">@item.CourseStatus.ShortName</td>
                                        @{
                                            if (item.Section != null)
                                            {
                                                <td width="5%">@item.Section.SectionId</td>
                                            }
                                            else
                                            {
                                                <td width="5%">---</td>

                                            }
                                        }

                                        <td>
                                            @*@Html.ActionLink("Edit", "Edit", "CourseForStudent", new {id = item.CourseForStudentsAcademicId}, null)|
                                            @Html.ActionLink("Delete", "Delete", "CourseForStudent", new {id = item.CourseForStudentsAcademicId}, null)*@
                                        </td>
                                        
                                    </tr>
                                  
                                }
                                <tr style="background: lightgrey;font-weight: bold">
                                    @{
                                        totalCredit += x;
                                        totalGrade += y;
                                        z = Math.Round(y/x, 2);
                                        cgpaCal = Math.Round(totalGrade/totalCredit, 2);
                                    }
                                    <td width="10%"></td>
                                    <td  width="30%">Credits Taken :</td>
                                    <td width="5%">@takenCredits</td>
                                    
                                    <td width="5%"></td>
                                    <td width="5%"></td>
                                    <td  width="5%"></td>
                                    <td width="5%"></td>
                                    <td width="5%">@y</td>
                                    <td width="5%">@earnedCredit</td>
                                    <th width="5%">@z</th>
                                    <th width="5%">@cgpaCal</th>
                                    <td width="5%"></td>
                                    <td width="5%"></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            </table>
                        }
                    }
                </div>
            </div>
        </div>
    }
}

UMS_MVC/Views/StudentMaster/GradeSheetPrintForSingleSemester.cshtml
@model List<UMS_MVC.DataModel.Models.Essential_Types.StudentIdentification>
@{
    ViewBag.Title = "Grade Sheet Controller";
    Layout = Session["LayoutMgr"].ToString();
    int tempIdForPrint = 0;
}
<div align="center">
    <h3 style="color: darkcyan;font-weight: bold">Grade Report Print</h3>
</div>

<label style="color: lightseagreen" class="breadcrumb">Filter Students List :</label>
<div class="well">
    <div class="row">
        @using (Html.BeginForm("GradeSheetPrintForSingleSemester", "StudentMaster"))
        {
            <div class="form-inline">
                <div class="form-group">
                    <label>Batch  </label>@Html.DropDownList("SemesterId", (SelectList)TempData["SemesterId"], "--Choose--", new { @class = "form-control ", Style = "width:100px" })
                </div>
                <div class="form-group">
                    <label>Department  </label> @Html.DropDownList("departmentId", (SelectList)ViewBag.DepartmentId, "--Choose--", new { @class = "form-control", style = "width: 180px" })
                </div>
                &nbsp;
                <div class="form-group">
                    <input type="text" name="studentId" id="studentId" class="form-control" style="width: 150px" placeholder="Search by Id" />
                    <input type="submit" class="btn btn-info btn-sm" value="Search">
                </div>
                <div class="form-group">
                    <button class="btn btn-danger btn-sm " onclick="location.href = '@Url.Action("GradeSheetPrintForSingleSemester", "StudentMaster")';return false; "><span class="glyphicon glyphicon-refresh"></span></button>
                </div>
            </div>
        }
    </div>
</div>

<div class="row">
    <div class="col-md-7">
        <div class="form-inline">
            <div class="form-group breadcrumb"><label style="color: darkcyan">Students List</label></div>
            <label class="form-group pull-right " style="color: darkcyan">Total @ViewBag.totalStudentCount result found.</label>
        </div>
        <div style="height: 450px;overflow-y: auto">
            <table class="table table-condensed table-bordered" style="border: black 1px;font-size: 11px">
                <tr style="background:#696969;color: white">
                    <th>Sl.</th>
                    <th>Student ID</th>
                    <th>Name</th>
                    <th></th>                
                </tr>
                @{
                    var x = 1;
                    foreach (var item in Model)
                    {
                        var stdID = item.StudentIdentificationId;
                        <tr>
                            <td>@x</td>
                            <td style="font-weight: bold">@item.StudentId</td>
                            <td>@Html.DisplayFor(modelItem => item.StudentInfo.StudentName)</td>
                            <td>
                               <div class="btn-group" role="group" aria-label="...">
                                <button class="btn btn-Custom7 btn-sm" onclick="loadGradeDetails('@stdID') "><span  class="glyphicon glyphicon-search"></span></button>
                                   <button title="Academic History" class="btn btn-Custom6 btn-sm" onclick="loadSection('@item.StudentIdentificationId')" data-toggle="modal" data-target="#courseListModal">
                                       <span style="font-size: 15px" class="glyphicon glyphicon-list-alt"></span> Show All
                                   </button>
                                   <button title="Print Options" class="btn btn-Custom3 btn-sm" onclick="loadPrintOption('@item.StudentIdentificationId')" data-toggle="modal" data-target="#courseListModal">
                                       <span style="font-size: 15px" class="glyphicon glyphicon-print"></span> Transcript *
                                   </button>
                                   
                                   @*@Html.ActionLink("Transcript", "GenrateTranscriptFinal", "DocumentPrint", new { studentId = item.StudentIdentificationId,type=2 }, null)*@
                               </div>
                            </td>
                           
                        </tr>
                        x++;
                    }
                }

            </table>
        </div>        
    </div>
    <div class="col-md-5">
        <h4 style="color: #008b8b; font-weight: bold"><u>Grade Report</u></h4>
        <div id="loadGradeSheet">
        </div>
    </div>
</div>

<div class="modal fade " id="courseListModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="min-width: 850px">
        <div class="modal-content">
            <div class="modal-header" >
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                
            </div>
            <div class="modal-body" id="studentCourseList">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $('#SemesterId').change(function() {

            $("input[type=submit]").click();

        });
        $("#departmentId").change(function() {
            $("input[type=submit]").click();
        });

        function loadGradeDetails(id) {
            $('#loadGradeSheet').load('@Url.Action("StudentGradeSheetDetails", "StudentMaster")', { sIdForStudentDetails: id });

        }

        function loadSection(stdID) {
            $('#studentCourseList').load('@Url.Action("AllDetailsOfSemester", "StudentMaster")', { sIID: stdID });
        }

        function loadPrintOption(sIId) {
            $('#studentCourseList').load('@Url.Action("ShowTranscriptPrintOptions", "StudentMaster")', { id: sIId });
        }
    </script>
}

UMS_MVC/Views/StudentMaster/StudentMastersControllers.cshtml
@using UMS_MVC.DataModel.Models.Essential_Types
@{
    ViewBag.Title = "Student Masters Controllers";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

    var studentIdentity = (StudentIdentification) ViewData["StudentIdentity"];
    var studentInfo = (StudentInfo) ViewData["StudentInfo"];
    var studentAcademic = (IEnumerable<StudentAcademicInfo>)ViewData["StudentAcademic"];
    var studentDocument = (DocumentAdding) ViewData["StudentDocument"];
    var studentPaymetRegis = (IEnumerable<PaymentRegistration>)ViewData["studentPaymetRegis"];
    var studentPayment = (IEnumerable<Payment>)ViewData["StudentPayment"];
    var registeredCourses = (IEnumerable<CourseForStudentsAcademic>)ViewData["registeredCourses"];
    var rebates = (IEnumerable<Rebate>) ViewData["rebate"];
}

<h3>Student Master Controllers</h3>
<div class="well">
    <div>
        @using (Html.BeginForm())
        {
            <input type="text" name="searchstudentId" />
            <input type="submit" class="hidden" />
        }
    </div>

    <div class="row">

        <div class="col-md-6">
            <dl class="dl-horizontal">
                <dt>Student Identity ID</dt>
                @{
                    if (studentIdentity != null)
                    {
                        <dd>@studentIdentity.StudentIdentificationId     @Html.ActionLink("Remove", "DeleteStudentIdentity", new { studentidentityId = studentIdentity.StudentIdentificationId, searchsVal = studentIdentity.StudentId })</dd>
                    }
                    else
                    {
                        <dd>No Data</dd>
                    }
                }
                <dt>Student Information ID</dt>
                @{
                    if (studentInfo != null)
                    {
                        <dd>@studentInfo.StudentInfoId  @Html.ActionLink("Remove", "DeleteStudentInformation", new { sudentIanfoId = studentInfo.StudentInfoId, searchsVal = studentIdentity.StudentId })</dd>
                    }
                    else
                    {
                        <dd>No data</dd>
                    }
                }
                <dt>Student Academic Info</dt>
                @{
                    if (studentAcademic != null)
                    {
                        <dd>Total @studentAcademic.Count() Infos @Html.ActionLink("Remove", "DeleteStudentAcademic", new { studentId = studentIdentity.StudentId, searchsVal = studentIdentity.StudentId })</dd>
                    }
                    else
                    {
                        <dd>No data</dd>
                    }
                }
                <dt>Student Document ID</dt>
                @{
                    if (studentDocument != null)
                    {
                        <dd>@studentDocument.DocumentAddingId @Html.ActionLink("Remove", "DeleteStudentDocument", new { documentId = studentDocument.DocumentAddingId, searchsVal = studentIdentity.StudentId })</dd>
                    }
                    else
                    {
                        <dd>No data</dd>
                    }
                }
                <dt>Student Payment Regis</dt>
                @{
                    if (studentPaymetRegis != null)
                    {
                        <dd>Total @studentPaymetRegis.Count() registrations @Html.ActionLink("Remove", "DeletePaymentRegis", new { studentId = studentIdentity.StudentIdentificationId, searchsVal = studentIdentity.StudentId })</dd>
                    }
                    else
                    {
                        <dd>Total 0 registrations</dd>
                    }
                }
                <dt>Student payments</dt>
                @{
                    if (studentPayment != null)
                    {
                        <dd>Total @studentPayment.Count() payments</dd>
                    }
                    else
                    {
                        <dd>Total 0 payments</dd>

                    }
                }
                <dt>Student Rebates</dt>
                @{
                    if (rebates != null)
                    {
                        <dd>Total @rebates.Count() Rebates @Html.ActionLink("Remove", "DeleteRebates", new { studentId = studentIdentity.StudentIdentificationId, searchsVal = studentIdentity.StudentId })</dd>
                    }
                    else
                    {
                        <dd>Total 0 rebates</dd>

                    }
                }
                <dt>Student Course Taken</dt>
                @{
                    if (registeredCourses != null)
                    {
                        <dd>Total @registeredCourses.Count() courses Taken @Html.ActionLink("Remove", "DeleteRegisteredCourses", new { studentId = studentIdentity.StudentIdentificationId, searchsVal = studentIdentity.StudentId })</dd>
                    }
                    else
                    {
                        <dd>Total 0 payments</dd>
                    }
                }
            </dl>
        </div>

        <div class="col-md-6">
            @{
                if (studentIdentity != null)
            {
        <label>Student's Name = @studentIdentity.StudentInfo.StudentName</label><br />
        <label>Students Id = @studentIdentity.StudentId</label><br />
        <label>Department = @studentIdentity.Department.DepartmentName</label><br />
        <label>School = @studentIdentity.School.SchoolName</label>
            }
            }
        </div>
    </div>
</div>